<?php
/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *  Which path of the site we are using to display help
 *
 * @param arg
 *  Array that holds the current path as returned form arg() function
 */
function current_posts_help($path, $arg) {
    switch ($path) {
        case "admin/help#current_posts":
            // passing text trough the t function makes the text translatable
            return '<p>' . t("Displays links to nodes created on this date") . '</p>';
            break;
    }
}

/**
 * Implements hook_block_info().
 *
 * method that tells Drupal what blocks this module creates
 */
function current_posts_block_info() {
    $blocks['current_posts'] = array(
        // The name that will appear in the block list
        'info' => t('Current posts'),
        // Default settings
        'cache' => DRUPAL_CACHE_PER_ROLE
    );
    return $blocks;
}

/**
 * Custom content function.
 *
 * Set beginning and end dates, retrieve posts from the database
 * saved in that time period.
 *
 * @return
 *  A result set of  the targeted posts.
 */
function current_posts_contents() {
    // Get todays date in form of an associative array
    $today = getdate();
    //Calculate the date of a week ago
    $start_time = mktime(0, 0, 0, $today['mon'], ($today['mday'] - 7), $today['year']);
    //Present timestamp in seconds
    $end_time = time();

    // use the database API to retrieve the current posts
    // create a query and execute it immediately
    $results = db_select('node', 'n')
        ->fields('n', array('nid', 'title', 'created'))
        ->condition('status', 1) //Published.
        ->condition('created', array($start_time, $end_time), 'BETWEEN')
        ->orderBy('created', 'DESC') //Most recent first.
        ->execute();
    return $results;
}

/**
 * Function that builds the block using the data
 *
 * @param delta
 *  describes what data should be loaded, with the switchcase we check if our block is being called and not a different one
 */
function current_posts_block_view($delta = '') {
    switch ($delta) {
        case 'current_posts':
            // Set a title for our block, passing text trough the t function makes the text translatable
            $block['subject'] = t('Current posts');
            // Check if current user has permission to view content, this check is very basic
            if (user_access('access content')) {
                // Use our custom function to retrieve data.
                $result = current_posts_contents();
                // Array to contain items for the block to render.
                $items = array();
                // Iterate over the result set and format as links.
                foreach ($result as $node) {
                    $items[] = array(
                        'data' => l($node->title, 'node/' . $node->nid),
                    );
                }
                // No content in the last week.
                if (empty($items)) {
                    $block['content'] = t('No posts available.');
                }
                else {
                    //Pass data through the theme function.
                    $block['content'] = theme('item_list', array('items' => $items));
                }
            }
            return $block;
            break;
    }
}
